---
- name: Perform common tasks
  import_role:
    name: _common

- name: Create the primary configuration directory
  file:
    path: "{{ config_directory }}"
    state: directory

- name: Create subdirectories
  file:
    path: "{{ config_directory }}/{{ item.path }}"
    state: directory
  with_filetree: templates
  when: item.state == "directory"

- name: Create configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.path }}"
  with_filetree: templates
  when: item.state == "file"
