---
- name: Perform common tasks
  import_role:
    name: _common

- name: Create subdirectories
  file:
    path: "{{ config_directory }}/{{ item.path }}"
    state: directory
  with_filetree: templates
  when: item.state == "directory"

- name: Create configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.path }}"
  with_filetree: templates
  when: item.state == "file"

- name: Create a list of all managed files
  set_fact:
    managed_files: >
      {{
        query('filetree', 'templates')
        | selectattr('state', 'equalto' ,'file')
        | map(attribute='path')
        | map('regex_replace', '^', config_directory + '/')
        | map('realpath')
        | list
      }}

- name: Query all present files
  find:
    paths: "{{ config_directory }}"
    recurse: yes
  register: present_files

- name: Create a list of files to delete
  set_fact:
    files_to_delete: >
      {{
        present_files['files']
        | map(attribute='path')
        | list
        | difference(managed_files)
      }}

- name: Delete unmanaged files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_delete }}"
