---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Create a list of all managed files
  ansible.builtin.set_fact:
    managed_files: >
      {{
        query('filetree', '{{ role_path }}/templates')
        | selectattr('state', 'equalto' ,'file')
        | map(attribute='path')
        | map('regex_replace', '^', config_directory + '/')
        | map('realpath')
        | list
      }}

- name: Query all present files
  ansible.builtin.find:
    paths: "{{ config_directory }}"
    recurse: true
  register: present_files

- name: Create a list of files to delete
  ansible.builtin.set_fact:
    files_to_delete: >
      {{
        present_files['files']
        | map(attribute='path')
        | list
        | difference(managed_files)
        | difference([
          config_directory + '/config.fish',
          config_directory + '/fish_variables',
        ])
      }}

- name: Delete unmanaged files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_delete }}"
