[lint]
select = ["ALL"]

ignore = [
    "D203", # one-blank-line-before-class (conflicts with D211)
    "D213", # multi-line-summary-second-line (conflicts with D212)

    # Ruff recommends to disable these when combined with the formatter.
    "COM812", # missing-trailing-comma
    "ISC001", # single-line-implicit-string-concatenation
]

[lint.per-file-ignores]
"scripts/*" = [
    "INP001", # implicit-namespace-package
    "T201", # print
]
