---
- name: Setup and configure dotfiles
  hosts: all
  roles:
    - fish
    - neovim
    - rofi
    - sway
    - dotfiles
    - "{{ terminal }}"
  vars:
    # If the environment variable `XDG_CONFIG_HOME` is not defined, use
    # `$HOME/.config` instead.
    user_home: "{{ ansible_env['HOME'] }}"
    config_home: "{{ ansible_env['XDG_CONFIG_HOME'] | default (user_home +'/.config') }}"
    install_dependencies: true
    terminal: termite
