---
- name: Setup and configure dotfiles
  hosts: all
  roles:
    # This role must come first as it creates a directory used by other roles
    - systemd

    - fish
    - starship
    - bash
    - firefox
    - thunderbird
    - neovim
    - rofi
    - sway
    - swaylock
    - i3status
    - mako
    - kanshi
    - tmux
    - fontconfig
    - zathura
    - "terminals/{{ terminal }}"
  vars_files:
    - theme.yml
    - variables.yml
