---
- name: Setup and configure dotfiles
  hosts: all
  vars_files:
    - theme.json
    - variables.yml
  tasks:
    - name: Import and tag each role
      block:
        - name: Apply role `user`
          ansible.builtin.import_role:
            name: user
          tags:
            - user

        - name: Apply role `neovim`
          ansible.builtin.import_role:
            name: neovim
          tags:
            - neovim

        - name: Apply role `sway`
          ansible.builtin.import_role:
            name: sway
          tags:
            - sway
