---
- name: Setup and configure dotfiles
  hosts: all
  roles:
    - fish
    - neovim
    - rofi
    - sway
    - dotfiles
    - fontconfig
    - "terminals/{{ terminal }}"
  vars_files:
    - variables.yml
