---
- name: Setup and configure dotfiles
  hosts: all
  roles:
    - fish
    - firefox
    - thunderbird
    - neovim
    - rofi
    - sway
    - tmux
    - fontconfig
    - zathura
    - "terminals/{{ terminal }}"
  vars_files:
    - theme.yml
    - variables.yml
