---
- name: Setup and configure dotfiles
  hosts: all
  vars_files:
    - theme.json
    - variables.yml
  tasks:
    - name: Import and tag each role
      block:
        # This role must come first as it creates a directory used by other roles
        - name: Apply role `systemd`
          ansible.builtin.import_role:
            name: systemd
          tags:
            - systemd

        - name: Apply role `user`
          ansible.builtin.import_role:
            name: user
          tags:
            - user

        - name: Apply role `fish`
          ansible.builtin.import_role:
            name: fish
          tags:
            - fish

        - name: Apply role `thunderbird`
          ansible.builtin.import_role:
            name: thunderbird
          tags:
            - thunderbird

        - name: Apply role `neovim`
          ansible.builtin.import_role:
            name: neovim
          tags:
            - neovim

        - name: Apply role `sway`
          ansible.builtin.import_role:
            name: sway
          tags:
            - sway

        - name: Apply role `swaylock`
          ansible.builtin.import_role:
            name: swaylock
          tags:
            - swaylock

        - name: Apply role `mako`
          ansible.builtin.import_role:
            name: mako
          tags:
            - mako

        - name: Apply role `kanshi`
          ansible.builtin.import_role:
            name: kanshi
          tags:
            - kanshi

        - name: Apply role `zathura`
          ansible.builtin.import_role:
            name: zathura
          tags:
            - zathura
