---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Place systemd user service
  ansible.builtin.copy:
    src: kanshi.service
    dest: "{{ config_home }}/systemd/user/kanshi.service"
    mode: u=rw,g=r,o=r

- name: Enable the kanshi service
  ansible.builtin.systemd:
    name: kanshi.service
    scope: user
    enabled: true
