---
- name: Perform common tasks
  import_role:
    name: _common

- name: Place systemd user service
  copy:
    src: kanshi.service
    dest: "{{ config_home }}/systemd/user/kanshi.service"

- name: Enable the kanshi service
  systemd:
    name: kanshi.service
    scope: user
    enabled: yes
