---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Create subdirectories
  ansible.builtin.file:
    path: "{{ config_directory }}/{{ item.path }}"
    state: directory
    mode: u=rwx,g=rx,o=x
  with_filetree: data/
  when: item.state == "directory"

- name: Create configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.path }}"
    mode: u=rw,g=r,o=r
  with_filetree: data/
  when: item.state == "file"
