---
- name: Install dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - sway
    - swaylock
    - swayidle
    - i3status
    - wl-clipboard
    - tmux
    - pulseaudio
  when: install_dependencies | bool

- name: Create Sway config directory
  file:
    path: "{{ sway_directory }}"
    state: directory

- name: Create the main configuration file
  template:
    src: config
    dest: "{{ sway_directory }}/config"

- name: Place static files
  synchronize:
    src: .
    dest: "{{ sway_directory }}"

- name: Create swaylock config directory
  file:
    path: "{{ swaylock_directory }}"
    state: directory

- name: Create swaylock configuration file
  template:
    src: swaylock
    dest: "{{ swaylock_directory }}/config"

