- name: Create the primary configuration directory
  file:
    path: "{{ config_directory }}"
    state: directory

- name: Create subdirectories for configuration files
  file:
    path: "{{ config_directory }}/{{ item.path }}"
    state: directory
  with_filetree: "{{ ansible_parent_role_paths[0] }}/templates"
  when: item.state == "directory"

- name: Create configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.path }}"
  with_filetree: "{{ ansible_parent_role_paths[0] }}/templates"
  when: item.state == "file"
