---
- name: Create the primary configuration directory
  ansible.builtin.file:
    path: "{{ config_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=x

- name: Create subdirectories for configuration files
  ansible.builtin.file:
    path: "{{ config_directory }}/{{ item.path }}"
    state: directory
    mode: u=rwx,g=rx,o=x
  with_filetree: "{{ ansible_parent_role_paths[0] }}/templates"
  when: item.state == "directory"

- name: Create configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.path }}"
    mode: u=rw,g=r,o=r
  with_filetree: "{{ ansible_parent_role_paths[0] }}/templates"
  when: item.state == "file"
