---
- name: Perform common tasks
  import_role:
    name: _common

- name: Create the main configuration file
  template:
    src: "{{ config_file }}"
    dest: "{{ config_directory }}/{{ config_file }}"

- name: Create theme file
  template:
    src: rejva.rasi
    dest: "{{ config_directory }}/rejva.rasi"
