---
- name: Install dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - fzf
  when: install_dependencies | bool

- name: Create the main configuration file `init.nvim`
  template:
    src: init.vim
    dest: "{{ neovim_directory }}/init.vim"

- name: Place the additional configuration files
  synchronize:
    src: nvim/
    dest: "{{ neovim_directory }}"

- name: Setup the Python virtual environment
  pip:
    requirements: "{{ neovim_directory }}/requirements.txt"
    virtualenv: "{{ neovim_virtualenv }}"
    virtualenv_python: python3

- name: Create directory for vim-plug
  file:
    path: "{{ user_home }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install plugin manager vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"

- name: Install Neovim Plugins with vim-plug
  command: nvim '+PlugInstall --sync' +quitall

- name: Create Neovim plugin directory
  file:
    path: "{{ neovim_plugin_directory }}"
    state: directory

- name: Install Neovim plugins natively
  synchronize:
    src: plugins/
    dest: "{{ neovim_plugin_directory }}"
