---
- name: Create the main configuration file `config.fish`
  template:
    src: config.fish
    dest: "{{ fish_directory }}/config.fish"

- name: Place the additional configuration files
  synchronize:
    src: fish/
    dest: "{{ fish_directory }}"
