---
- name: Perform common tasks
  import_role:
    name: _common

- name: Create the main configuration file
  template:
    src: "{{ config_file }}"
    dest: "{{ config_directory }}/{{ config_file }}"

- name: Place static files
  synchronize:
    src: .
    dest: "{{ config_directory }}"

- name: Create swaylock config directory
  file:
    path: "{{ swaylock_directory }}"
    state: directory

- name: Create swaylock configuration file
  template:
    src: swaylock
    dest: "{{ swaylock_directory }}/config"

- name: Create i3status config directory
  file:
    path: "{{ i3status_directory }}"
    state: directory

- name: Create i3status configuration file
  template:
    src: i3status
    dest: "{{ i3status_directory }}/config"
