---
- name: Perform common tasks
  import_role:
    name: _common

- name: Place static files
  synchronize:
    src: .
    dest: "{{ config_directory }}"

- name: Add user to 'video' group, required for backlight utility 'light'
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: yes
