---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Add user to 'video' group, required for backlight utility 'light'
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: true
