---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Remove all paq-nvim data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ user_home }}/.local/share/nvim/site/pack/paqs"
    - "{{ user_home }}/.local/share/nvim/paq-lock.json"
