---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Setup the Python virtual environment
  ansible.builtin.pip:
    requirements: "{{ config_directory }}/requirements.txt"
    virtualenv: "{{ neovim_virtualenv }}"
    virtualenv_python: python3

- name: Create directory for package manager packer.nvim
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory
    mode: u=rwx,g=rx,o=x

- name: Clone Git repository for packer.nvim
  ansible.builtin.git: # noqa: latest[git]
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Update Neovim plugins with packer.nvim
  ansible.builtin.command: nvim --headless +"autocmd User PackerComplete quitall" +PackerSync
  changed_when: true

- name: Create directory for vim-plug
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/nvim/site/autoload"
    state: directory
    mode: u=rwx,g=rx,o=x

- name: Install plugin manager vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"
    mode: u=rw,g=r,o=r

- name: Update Neovim Plugins with vim-plug
  ansible.builtin.command: nvim '+PlugUpdate --sync' +quitall
  changed_when: true
