---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Remove packages installed by paq-nvim
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    state: absent
