---
- name: Perform common tasks
  import_role:
    name: _common

- name: Setup the Python virtual environment
  pip:
    requirements: "{{ config_directory }}/requirements.txt"
    virtualenv: "{{ neovim_virtualenv }}"
    virtualenv_python: python3

- name: Create directory for package manager packer.nvim
  file:
    path: "{{ user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory

- name: Clone Git repository for packer.nvim
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Install Neovim plugins with packer.nvim
  command: nvim --headless +"autocmd User PackerComplete quitall" +PackerSync

- name: Create directory for vim-plug
  file:
    path: "{{ user_home }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install plugin manager vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"

- name: Install Neovim Plugins with vim-plug
  command: nvim '+PlugInstall --sync' +quitall
