---
- name: Perform common tasks
  ansible.builtin.import_role:
    name: _common

- name: Setup the Python virtual environment
  ansible.builtin.pip:
    requirements: "{{ config_directory }}/requirements.txt"
    virtualenv: "{{ neovim_virtualenv }}"
    virtualenv_python: python3

- name: Clone Git repository for paq-nvim
  ansible.builtin.git: # noqa: latest[git]
    repo: https://github.com/savq/paq-nvim.git
    dest: "{{ user_home }}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    depth: 1

- name: Update Neovim Plugins with Paq
  ansible.builtin.command: nvim --headless +"autocmd User PaqDoneSync quitall" +PaqSync
  register: paq_command
  changed_when: |
    'Paq: Nothing to remove' not in paq_command.stderr
    or 'Paq: sync complete. 0 ok; 0 errors' not in paq_command.stderr

- name: Remove all vim-plug data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ user_home }}/.local/share/nvim/site/autoload/plug.vim"
    - "{{ user_home }}/.local/share/nvim/plugged"
